# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Extra


class KolibriOvenFactoryStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    governorContractAddress: str
    initialDelegate: Optional[str]
    makeOvenOwner: Optional[str]
    minterContractAddress: str
    ovenProxyContractAddress: str
    ovenRegistryContractAddress: str
    state: str
