# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class KolibriOvenStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    borrowedTokens: str
    interestIndex: str
    isLiquidated: bool
    ovenProxyContractAddress: str
    owner: str
    stabilityFeeTokens: str
