# generated by datamodel-codegen:
#   filename:  default.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class DefaultParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
