# generated by datamodel-codegen:
#   filename:  liquidate.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class LiquidateParameter(BaseModel):
    pass

    class Config:
        extra = Extra.forbid
