# generated by datamodel-codegen:
#   filename:  updateState.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class UpdateStateParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    address: str
    nat: str
    int_0: str
    int_1: str
    bool: bool
