# generated by datamodel-codegen:
#   filename:  balances_value.json

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel, Extra


class BalancesValue(BaseModel):
    class Config:
        extra = Extra.forbid

    approvals: Dict[str, str]
    balance: str
