# generated by datamodel-codegen:
#   filename:  burn.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class BurnParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    address: str
    value: str
