# generated by datamodel-codegen:
#   filename:  setInitialDelegate.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class SetInitialDelegateParameter(BaseModel):
    __root__: Optional[str]
