# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Extra


class StabilityFundStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    administratorContractAddress: str
    governorContractAddress: str
    ovenRegistryContractAddress: str
    savingsPoolContractAddress: str
    sendAllTokens_destination: Optional[str]
    state: str
    tokenContractAddress: str
